import { useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, ChevronDown, CircleHelp, Filter, LayoutDashboard, ListChecks, MessageSquareText, MoreHorizontal, Plus, Search, Settings, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react';
import { candidates as seed, Candidate, Stage, stages, vacancies } from './data';

const scoreTone=(n:number)=>n>=85?'great':n>=70?'good':'low';
type VacancyOption={id?:number;name:string;active:boolean;count:number;newCount:number};
type Criterion={id?:number;name:string;description:string;weight:number;position:number};
type AppTab='board'|'candidates'|'vacancies'|'dialogs'|'criteria'|'settings';
type HhState={connected:boolean;loading:boolean;message?:string};
const tabTitles:Record<AppTab,{title:string;subtitle:string}>={
 board:{title:'Воронка кандидатов',subtitle:'Входящие отклики из hh.ru'},
 candidates:{title:'Кандидаты',subtitle:'Все входящие кандидаты по активным вакансиям'},
 vacancies:{title:'Вакансии',subtitle:'Активные вакансии и количество откликов'},
 dialogs:{title:'Диалоги',subtitle:'Кандидаты, с которыми идёт общение в hh.ru'},
 criteria:{title:'Критерии оценки',subtitle:'Настройте веса скоринга отдельно для каждой вакансии'},
 settings:{title:'Настройки',subtitle:'Подключения и синхронизация CRM'},
};
export function App(){
 const [items,setItems]=useState(seed); const [selected,setSelected]=useState<Candidate|null>(null); const [vacancy,setVacancy]=useState('Все вакансии'); const [tab,setTab]=useState<AppTab>('board'); const [query,setQuery]=useState('');
 const [vacancyOptions,setVacancyOptions]=useState<VacancyOption[]>(vacancies);
 const [hh,setHh]=useState<HhState>({connected:false,loading:true});
 useEffect(()=>{fetch('/api/hh/status').then(r=>r.json()).then(data=>setHh({connected:Boolean(data.hh?.connected),loading:false})).catch(()=>setHh({connected:false,loading:false}))},[]);
 useEffect(()=>{fetch('/api/crm').then(r=>r.json()).then(data=>{if(data.vacancies?.length)setVacancyOptions(data.vacancies.map((v:{id:number;name:string})=>({id:v.id,name:v.name,active:true,count:0,newCount:0})));if(data.candidates?.length)setItems(data.candidates.map((c:any)=>{const parts=String(c.name).trim().split(/\s+/);return {...c,stage:c.stage as Stage,score:c.score??0,updated:'недавно',initials:parts.slice(0,2).map((p:string)=>p[0]).join('').toUpperCase(),color:'#dce7e2',factors:c.factors||[]}}))}).catch(()=>{})},[]);
 const visible=useMemo(()=>items.filter(c=>(vacancy==='Все вакансии'||c.vacancy===vacancy)&&(!query||`${c.name} ${c.role} ${c.vacancy}`.toLowerCase().includes(query.toLowerCase()))),[items,vacancy,query]);
 const move=(id:number,stage:Stage)=>{setItems(x=>x.map(c=>c.id===id?{...c,stage}:c));setSelected(s=>s?.id===id?{...s,stage}:s);fetch(`/api/candidates/${id}/stage`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage})}).catch(()=>{})};
 const syncHh=async()=>{setHh(s=>({...s,loading:true,message:undefined}));try{const r=await fetch('/api/hh/sync',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);setHh({connected:true,loading:false,message:`${data.candidates} откликов`})}catch(error){setHh(s=>({...s,loading:false,message:error instanceof Error?error.message:'Ошибка'}))}};
 return <div className="shell">
  <aside><div className="brand"><span>SG</span><b>HR CRM</b></div><nav><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}><LayoutDashboard/>Воронка</button><button className={tab==='candidates'?'active':''} onClick={()=>setTab('candidates')}><Users/>Кандидаты</button><button className={tab==='vacancies'?'active':''} onClick={()=>setTab('vacancies')}><BriefcaseBusiness/>Вакансии</button><button className={tab==='dialogs'?'active':''} onClick={()=>setTab('dialogs')}><MessageSquareText/>Диалоги <i>{items.filter(c=>c.stage==='Диалог').length}</i></button><button className={tab==='criteria'?'active':''} onClick={()=>setTab('criteria')}><ListChecks/>Критерии</button></nav><div className="aside-bottom"><button onClick={()=>location.assign('mailto:sg@service.guru')}><CircleHelp/>Поддержка</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings/>Настройки</button><div className="profile"><div>СГ</div><span><b>Сергей</b><small>Администратор</small></span><ChevronDown/></div></div></aside>
  <main><header><div><h1>{tabTitles[tab].title}</h1><p>{tabTitles[tab].subtitle}</p></div><div className="header-actions"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск кандидата"/></label><button className="primary" onClick={syncHh} disabled={hh.loading}><SlidersHorizontal/>{hh.loading?'Обновление…':'Обновить из HH'}</button></div></header>
  {tab==='board'&&<Board items={items} visible={visible} vacancy={vacancy} vacancies={vacancyOptions} setVacancy={setVacancy} hh={hh} syncHh={syncHh} select={setSelected}/>}
  {tab==='candidates'&&<CandidatesView items={visible} select={setSelected}/>}
  {tab==='vacancies'&&<VacanciesView vacancies={vacancyOptions} items={items} open={name=>{setVacancy(name);setTab('board')}}/>}
  {tab==='dialogs'&&<CandidatesView items={visible.filter(c=>c.stage==='Диалог')} select={setSelected} empty="Кандидатов на этапе «Диалог» пока нет."/>}
  {tab==='criteria'&&<Criteria vacancies={vacancyOptions.filter(v=>v.id)}/>}
  {tab==='settings'&&<SettingsView hh={hh} syncHh={syncHh}/>}</main>
  {selected&&<CandidatePanel candidate={selected} close={()=>setSelected(null)} move={move}/>} </div>
}

function Board({items,visible,vacancy,vacancies,setVacancy,hh,syncHh,select}:{items:Candidate[];visible:Candidate[];vacancy:string;vacancies:VacancyOption[];setVacancy:(value:string)=>void;hh:HhState;syncHh:()=>void;select:(candidate:Candidate)=>void}){
 return <><section className="toolbar"><div className="select-wrap"><BriefcaseBusiness/><select value={vacancy} onChange={e=>setVacancy(e.target.value)}><option>Все вакансии</option>{vacancies.map(v=><option key={v.name}>{v.name}</option>)}</select></div>{hh.connected?<button className="sync sync-button" onClick={syncHh} disabled={hh.loading}><span></span>{hh.loading?'Синхронизация…':'hh.ru подключен'} <small>{hh.message||'обновить'}</small></button>:<button className="connect-hh" onClick={()=>location.assign('/api/hh/connect')} disabled={hh.loading}><span></span>{hh.loading?'Проверяем hh.ru…':'Подключить hh.ru'}</button>}</section><section className="stats"><div><small>Всего кандидатов</small><strong>{visible.length}</strong><em>в выборке</em></div><div><small>Средний скор</small><strong>{Math.round(visible.reduce((a,c)=>a+c.score,0)/(visible.filter(c=>c.score>0).length||1))}</strong><em>из 100</em></div><div><small>Ждут ответа</small><strong>{visible.filter(c=>c.stage==='Новый').length}</strong><em className="warn">новые</em></div><div><small>На интервью</small><strong>{items.filter(c=>c.stage==='Интервью').length}</strong><em>кандидатов</em></div></section><section className="board">{stages.slice(0,6).map(stage=><div className="column" key={stage}><div className="column-head"><span className={'dot '+stage.toLowerCase()}></span><b>{stage}</b><small>{visible.filter(c=>c.stage===stage).length}</small><MoreHorizontal/></div><div className="cards">{visible.filter(c=>c.stage===stage).map(c=><article key={c.id} onClick={()=>select(c)}><div className="candidate"><div className="avatar" style={{background:c.color}}>{c.initials}</div><div><b>{c.name}</b><small>{c.role}</small></div><span className={'score '+scoreTone(c.score)}>{c.score||'—'}</span></div><div className="meta"><span>{c.location}</span><span>{c.experience}</span></div><footer><span>{c.updated}</span><ChevronDown/></footer></article>)}</div></div>)}</section></>
}

function CandidatesView({items,select,empty='Кандидаты не найдены.'}:{items:Candidate[];select:(candidate:Candidate)=>void;empty?:string}){
 if(!items.length)return <section className="empty-state">{empty}</section>;
 return <section className="data-list">{items.map(c=><button key={c.id} onClick={()=>select(c)}><span className="avatar" style={{background:c.color}}>{c.initials}</span><span className="list-main"><b>{c.name}</b><small>{c.role} · {c.vacancy}</small></span><span>{c.location}</span><span className="stage-pill">{c.stage}</span><strong className={'score '+scoreTone(c.score)}>{c.score||'—'}</strong><ChevronDown/></button>)}</section>
}

function VacanciesView({vacancies,items,open}:{vacancies:VacancyOption[];items:Candidate[];open:(name:string)=>void}){
 return <section className="vacancy-list">{vacancies.map(v=>{const related=items.filter(c=>c.vacancy===v.name);return <button key={v.name} onClick={()=>open(v.name)}><span><b>{v.name}</b><small>Активная вакансия hh.ru</small></span><strong>{related.length}</strong><small>кандидатов</small><ChevronDown/></button>})}</section>
}

function SettingsView({hh,syncHh}:{hh:HhState;syncHh:()=>void}){
 return <section className="settings-view"><div><span className={hh.connected?'status-dot connected-dot':'status-dot'}></span><span><b>Интеграция hh.ru</b><small>{hh.connected?'Подключена и готова к синхронизации':'Требуется подключение аккаунта работодателя'}</small></span>{hh.connected?<button className="primary" onClick={syncHh} disabled={hh.loading}>{hh.loading?'Обновление…':'Синхронизировать'}</button>:<button className="primary" onClick={()=>location.assign('/api/hh/connect')}>Подключить</button>}</div><div><span className="status-dot connected-dot"></span><span><b>OpenAI</b><small>Ключ хранится в Railway и используется только сервером</small></span></div></section>
}

function Criteria({vacancies}:{vacancies:VacancyOption[]}){
 const [vacancyId,setVacancyId]=useState<number|undefined>();
 const [criteria,setCriteria]=useState<Criterion[]>([]);
 const [loading,setLoading]=useState(false);
 const [message,setMessage]=useState('');
 useEffect(()=>{if(!vacancyId&&vacancies[0]?.id)setVacancyId(vacancies[0].id)},[vacancies,vacancyId]);
 useEffect(()=>{if(!vacancyId)return;setLoading(true);setMessage('');fetch(`/api/vacancies/${vacancyId}/criteria`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setCriteria(data.criteria?.length?data.criteria:[{name:'Профильный опыт',description:'Релевантный опыт для этой вакансии',weight:40,position:0},{name:'Ключевые навыки',description:'Совпадение навыков с требованиями вакансии',weight:35,position:1},{name:'Релевантность задач',description:'Сходство прошлых задач с будущей ролью',weight:25,position:2}])}).catch(e=>setMessage(e.message||'Не удалось загрузить критерии')).finally(()=>setLoading(false))},[vacancyId]);
 const total=criteria.reduce((sum,item)=>sum+item.weight,0);
 const update=(index:number,patch:Partial<Criterion>)=>setCriteria(items=>items.map((item,i)=>i===index?{...item,...patch}:item));
 const add=()=>setCriteria(items=>[...items,{name:'Новый критерий',description:'',weight:0,position:items.length}]);
 const remove=(index:number)=>setCriteria(items=>items.filter((_,i)=>i!==index));
 const save=async()=>{if(!vacancyId||total!==100)return;setLoading(true);setMessage('');try{const r=await fetch(`/api/vacancies/${vacancyId}/criteria`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({criteria})});const data=await r.json();if(!r.ok)throw new Error(data.error);setCriteria(data.criteria);setMessage('Критерии сохранены')}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить')}finally{setLoading(false)}};
 const score=async()=>{if(!vacancyId||total!==100)return;setLoading(true);setMessage('AI оценивает до 10 новых кандидатов. Это может занять несколько минут…');try{const saved=await fetch(`/api/vacancies/${vacancyId}/criteria`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({criteria})});const savedData=await saved.json();if(!saved.ok)throw new Error(savedData.error);setCriteria(savedData.criteria);const r=await fetch(`/api/vacancies/${vacancyId}/score`,{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage(data.scored?`Готово: оценено кандидатов — ${data.scored}. Обновите воронку, чтобы увидеть результаты.`:'Новых кандидатов без оценки не найдено.')}catch(e){setMessage(e instanceof Error?e.message:'Не удалось запустить скоринг')}finally{setLoading(false)}};
 if(!vacancies.length)return <section className="criteria-page"><p>Сначала синхронизируйте активные вакансии из hh.ru.</p></section>;
 return <section className="criteria-page">
  <div className="criteria-title"><div><label className="criteria-vacancy">Вакансия<select value={vacancyId||''} onChange={e=>setVacancyId(Number(e.target.value))}>{vacancies.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><p className={total===100?'total-ok':'total-error'}>Сумма весов: {total}% {total!==100&&'· должна быть 100%'}</p></div><div className="criteria-actions"><button className="ghost-action" onClick={add}><Plus/>Добавить</button><button className="ghost-action ai-score-action" onClick={score} disabled={loading||total!==100}><Sparkles/>Оценить 10</button><button className="primary" onClick={save} disabled={loading||total!==100}>{loading?'Подождите…':'Сохранить'}</button></div></div>
  {criteria.map((item,i)=><div className="criterion" key={`${i}-${item.id||'new'}`}><span className="drag">⋮⋮</span><div className="criterion-fields"><label>Название критерия<input value={item.name} maxLength={120} onChange={e=>update(i,{name:e.target.value})}/></label><label>Описание для AI<textarea value={item.description} maxLength={1500} rows={3} onChange={e=>update(i,{description:e.target.value})}/><small>{item.description.length}/1500</small></label></div><input type="range" min="0" max="100" value={item.weight} onChange={e=>update(i,{weight:Number(e.target.value)})}/><strong>{item.weight}%</strong><button className="remove-criterion" title="Удалить критерий" onClick={()=>remove(i)}><X/></button></div>)}
  {message&&<p className="criteria-message">{message}</p>}<div className="ai-note"><Sparkles/><div><b>Как считается итоговый скор</b><p>AI оценивает только профессиональные данные резюме по заданным критериям, затем применяет веса. Чувствительные персональные признаки исключены. Оценка носит рекомендательный характер, финальное решение принимает рекрутер.</p></div></div>
 </section>
}
function CandidatePanel({candidate:c,close,move}:{candidate:Candidate;close:()=>void;move:(id:number,s:Stage)=>void}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><span>Карточка кандидата</span><button className="icon" onClick={close}><X/></button></div><div className="person"><div className="avatar large" style={{background:c.color}}>{c.initials}</div><div><h2>{c.name}</h2><p>{c.role}</p></div><span className={'score big '+scoreTone(c.score)}>{c.score}</span></div><div className="facts"><span><small>Локация</small>{c.location}</span><span><small>Опыт</small>{c.experience}</span><span><small>Ожидания</small>{c.salary}</span></div><label className="stage-select">Этап<select value={c.stage} onChange={e=>move(c.id,e.target.value as Stage)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><div className="panel-section"><div className="section-head"><h3>AI-оценка</h3><Sparkles/></div>{c.factors.map(f=><div className="factor" key={f.label}><div><b>{f.label}</b><small>{f.note}</small></div><div className="bar"><i style={{width:f.score+'%'}}></i></div><strong>{f.score}</strong></div>)}</div><div className="panel-section"><div className="section-head"><h3>Диалог в hh.ru</h3><span className="connected">подключен</span></div><div className="message incoming">Анна, добрый день! Рассматриваете сейчас новые предложения?</div><div className="message outgoing">Здравствуйте! Да, особенно продуктовые команды с B2B-направлением.</div><button className="reply"><MessageSquareText/>Открыть переписку</button></div></aside></div>}
