import { useMemo, useState } from 'react';
import { BriefcaseBusiness, ChevronDown, CircleHelp, Filter, LayoutDashboard, ListChecks, MessageSquareText, MoreHorizontal, Plus, Search, Settings, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react';
import { candidates as seed, Candidate, Stage, stages, vacancies } from './data';

const scoreTone=(n:number)=>n>=85?'great':n>=70?'good':'low';
export function App(){
 const [items,setItems]=useState(seed); const [selected,setSelected]=useState<Candidate|null>(null); const [vacancy,setVacancy]=useState('Все вакансии'); const [tab,setTab]=useState<'board'|'criteria'>('board');
 const visible=useMemo(()=>items.filter(c=>vacancy==='Все вакансии'||c.vacancy===vacancy),[items,vacancy]);
 const move=(id:number,stage:Stage)=>{setItems(x=>x.map(c=>c.id===id?{...c,stage}:c));setSelected(s=>s?.id===id?{...s,stage}:s)};
 return <div className="shell">
  <aside><div className="brand"><span>SG</span><b>HR CRM</b></div><nav><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}><LayoutDashboard/>Воронка</button><button><Users/>Кандидаты</button><button><BriefcaseBusiness/>Вакансии</button><button><MessageSquareText/>Диалоги <i>3</i></button><button className={tab==='criteria'?'active':''} onClick={()=>setTab('criteria')}><ListChecks/>Критерии</button></nav><div className="aside-bottom"><button><CircleHelp/>Поддержка</button><button><Settings/>Настройки</button><div className="profile"><div>СГ</div><span><b>Сергей</b><small>Администратор</small></span><ChevronDown/></div></div></aside>
  <main><header><div><h1>{tab==='board'?'Воронка кандидатов':'Критерии оценки'}</h1><p>{tab==='board'?'Входящие отклики из hh.ru':'Настройте веса скоринга отдельно для каждой вакансии'}</p></div><div className="header-actions"><label className="search"><Search/><input placeholder="Поиск кандидата"/></label><button className="icon"><Filter/></button><button className="primary"><Plus/>Добавить кандидата</button></div></header>
  {tab==='board'?<><section className="toolbar"><div className="select-wrap"><BriefcaseBusiness/><select value={vacancy} onChange={e=>setVacancy(e.target.value)}><option>Все вакансии</option>{vacancies.map(v=><option key={v.name}>{v.name}</option>)}</select></div><div className="sync"><span></span>hh.ru синхронизирован <small>5 мин назад</small></div><button className="ghost"><SlidersHorizontal/>Фильтры</button></section><section className="stats"><div><small>Всего кандидатов</small><strong>{visible.length}</strong><em>+12 за неделю</em></div><div><small>Средний скор</small><strong>{Math.round(visible.reduce((a,c)=>a+c.score,0)/(visible.length||1))}</strong><em>из 100</em></div><div><small>Ждут ответа</small><strong>3</strong><em className="warn">нужно внимание</em></div><div><small>На интервью</small><strong>{items.filter(c=>c.stage==='Интервью').length}</strong><em>на этой неделе</em></div></section><section className="board">{stages.slice(0,6).map(stage=><div className="column" key={stage}><div className="column-head"><span className={'dot '+stage.toLowerCase()}></span><b>{stage}</b><small>{visible.filter(c=>c.stage===stage).length}</small><MoreHorizontal/></div><div className="cards">{visible.filter(c=>c.stage===stage).map(c=><article key={c.id} onClick={()=>setSelected(c)}><div className="candidate"><div className="avatar" style={{background:c.color}}>{c.initials}</div><div><b>{c.name}</b><small>{c.role}</small></div><span className={'score '+scoreTone(c.score)}>{c.score}</span></div><div className="meta"><span>{c.location}</span><span>{c.experience}</span></div><footer><span>{c.updated}</span>{c.stage==='Диалог'&&<span className="unread">2 сообщения</span>}<ChevronDown/></footer></article>)}</div></div>)}</section></>:<Criteria/>}</main>
  {selected&&<CandidatePanel candidate={selected} close={()=>setSelected(null)} move={move}/>} </div>
}
function Criteria(){const [weights,setWeights]=useState([35,30,20,15]); const names=['Профильный опыт','Ключевые навыки','Релевантность проектов','Ответы в диалоге'];return <section className="criteria-page"><div className="criteria-title"><div><h2>Продуктовый дизайнер</h2><p>Сумма весов: {weights.reduce((a,b)=>a+b,0)}%</p></div><button className="primary"><Plus/>Добавить критерий</button></div>{names.map((n,i)=><div className="criterion" key={n}><span className="drag">⋮⋮</span><div><b>{n}</b><small>{['Опыт работы в продуктовых командах и B2B SaaS','Figma, дизайн-системы, прототипирование','Сходство прошлых задач с нашей вакансией','Мотивация, ожидания и ясность коммуникации'][i]}</small></div><input type="range" min="0" max="60" value={weights[i]} onChange={e=>setWeights(w=>w.map((v,j)=>j===i?+e.target.value:v))}/><strong>{weights[i]}%</strong><button className="icon"><MoreHorizontal/></button></div>)}<div className="ai-note"><Sparkles/><div><b>Как считается итоговый скор</b><p>AI оценивает резюме и ответы по каждому критерию, затем применяет заданные веса. Рекрутер видит оценку и объяснение, но принимает финальное решение самостоятельно.</p></div></div></section>}
function CandidatePanel({candidate:c,close,move}:{candidate:Candidate;close:()=>void;move:(id:number,s:Stage)=>void}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><span>Карточка кандидата</span><button className="icon" onClick={close}><X/></button></div><div className="person"><div className="avatar large" style={{background:c.color}}>{c.initials}</div><div><h2>{c.name}</h2><p>{c.role}</p></div><span className={'score big '+scoreTone(c.score)}>{c.score}</span></div><div className="facts"><span><small>Локация</small>{c.location}</span><span><small>Опыт</small>{c.experience}</span><span><small>Ожидания</small>{c.salary}</span></div><label className="stage-select">Этап<select value={c.stage} onChange={e=>move(c.id,e.target.value as Stage)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><div className="panel-section"><div className="section-head"><h3>AI-оценка</h3><Sparkles/></div>{c.factors.map(f=><div className="factor" key={f.label}><div><b>{f.label}</b><small>{f.note}</small></div><div className="bar"><i style={{width:f.score+'%'}}></i></div><strong>{f.score}</strong></div>)}</div><div className="panel-section"><div className="section-head"><h3>Диалог в hh.ru</h3><span className="connected">подключен</span></div><div className="message incoming">Анна, добрый день! Рассматриваете сейчас новые предложения?</div><div className="message outgoing">Здравствуйте! Да, особенно продуктовые команды с B2B-направлением.</div><button className="reply"><MessageSquareText/>Открыть переписку</button></div></aside></div>}
