export type Stage = 'Новый'|'Скрининг'|'Диалог'|'Интервью'|'Оффер'|'Нанят'|'Отказ';
export type Candidate = {id:number;name:string;role:string;vacancy:string;stage:Stage;score:number;location:string;salary:string;experience:string;updated:string;initials:string;color:string;factors:{label:string;score:number;note:string}[]};
export const stages:Stage[]=['Новый','Скрининг','Диалог','Интервью','Оффер','Нанят','Отказ'];
export const candidates:Candidate[]=[
 {id:1,name:'Анна Морозова',role:'Senior Product Designer',vacancy:'Продуктовый дизайнер',stage:'Диалог',score:91,location:'Москва · удаленно',salary:'230 000 ₽',experience:'6 лет',updated:'12 мин',initials:'АМ',color:'#d7e7df',factors:[{label:'Продуктовый опыт',score:96,note:'5 лет в B2B SaaS'},{label:'Figma и дизайн-системы',score:94,note:'Вела DS на 40+ компонентов'},{label:'Исследования',score:82,note:'Регулярные интервью и JTBD'}]},
 {id:2,name:'Илья Соколов',role:'Backend-разработчик',vacancy:'Senior Backend Engineer',stage:'Новый',score:84,location:'Санкт-Петербург',salary:'280 000 ₽',experience:'7 лет',updated:'28 мин',initials:'ИС',color:'#e5ded3',factors:[{label:'Go / PostgreSQL',score:92,note:'4 года production-опыта'},{label:'Highload',score:86,note:'Сервисы до 8k RPS'},{label:'Лидерство',score:68,note:'Менторил двух разработчиков'}]},
 {id:3,name:'Мария Волкова',role:'Продуктовый аналитик',vacancy:'Продуктовый аналитик',stage:'Скрининг',score:78,location:'Казань · удаленно',salary:'190 000 ₽',experience:'4 года',updated:'1 ч',initials:'МВ',color:'#dce2ec',factors:[{label:'SQL',score:90,note:'Сложные запросы и оптимизация'},{label:'A/B-тесты',score:76,note:'12 экспериментов за год'},{label:'Python',score:67,note:'Базовый pandas'}]},
 {id:4,name:'Дмитрий Орлов',role:'Senior Product Designer',vacancy:'Продуктовый дизайнер',stage:'Интервью',score:87,location:'Москва',salary:'250 000 ₽',experience:'8 лет',updated:'вчера',initials:'ДО',color:'#eadedb',factors:[{label:'Продуктовый опыт',score:90,note:'Fintech и e-commerce'},{label:'Figma и дизайн-системы',score:88,note:'Создавал DS с нуля'},{label:'Исследования',score:80,note:'Есть опыт usability-тестов'}]},
 {id:5,name:'Елена Белова',role:'Backend-разработчик',vacancy:'Senior Backend Engineer',stage:'Оффер',score:93,location:'Новосибирск · удаленно',salary:'270 000 ₽',experience:'9 лет',updated:'2 дн',initials:'ЕБ',color:'#d9e6e7',factors:[{label:'Go / PostgreSQL',score:97,note:'Сильный профиль'},{label:'Highload',score:94,note:'Платежная платформа'},{label:'Лидерство',score:86,note:'Tech lead команды из 6 человек'}]},
 {id:6,name:'Алексей Лебедев',role:'Продуктовый аналитик',vacancy:'Продуктовый аналитик',stage:'Отказ',score:52,location:'Самара',salary:'210 000 ₽',experience:'2 года',updated:'3 дн',initials:'АЛ',color:'#e4e0d8',factors:[{label:'SQL',score:72,note:'Средний уровень'},{label:'A/B-тесты',score:48,note:'Нет самостоятельных запусков'},{label:'Python',score:36,note:'Только учебные проекты'}]}
];
export const vacancies=[{name:'Продуктовый дизайнер',active:true,count:18,newCount:4},{name:'Senior Backend Engineer',active:true,count:31,newCount:7},{name:'Продуктовый аналитик',active:true,count:12,newCount:1}];
